---
to: src/pages/<%=name%>/index.tsx
---
<%
  PageComponentName = h.changeCase.pascal(name) + 'Page'
  PropsInterface = 'I' + PageComponentName + 'Props'
%>
import Head from 'next/head'

import { PageContainer, Heading1 } from '@components/styled' 

export interface <%= PropsInterface %> {}

export default function <%= PageComponentName %>(props: <%= PropsInterface %>) {
  return (
    <PageContainer>
      <Head>
        <title>New Page content | React Animations Prototyping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading1>New Page content</Heading1>
      </main>
    </PageContainer>
  )
}
