import { FC } from 'react'
import Head from 'next/head'
import Link from 'next/link'

import { Heading1, PageContainer, PageContent } from '@components/styled'

const HomePage: FC = () => {
  return (
    <PageContainer>
      <Head>
        <title>React Animations Prototyping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContent>
        <Heading1>React Animations Prototyping</Heading1>

        <nav>
          <ul>
            <li>
              <Link href="/locomotive-scroll">
                <a>Locomotive Scroll</a>
              </Link>
            </li>
            <li>
              <Link href="/mission-template">
                <a>Mission Template</a>
              </Link>
            </li>
            <li>
              <Link href="/react-parallax">
                <a>React Parallax</a>
              </Link>
            </li>
          </ul>
        </nav>
      </PageContent>
    </PageContainer>
  )
}

export default HomePage
