import Head from 'next/head'
import { FC } from 'react'
import { Parallax, ParallaxProvider } from 'react-scroll-parallax'

import {
  Heading1,
  PageContainer,
  PageContent,
  BannerSection,
  DemoSection,
  Heading2,
  DemoColumns,
  Column,
  Box,
  ParallaxContainer,
} from '@components/styled'

const HomePage: FC = () => {
  return (
    <PageContainer>
      <Head>
        <title>React Parallax | React Animations Prototyping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContent>
        <BannerSection>
          <ParallaxProvider>
            <Parallax y={[-250, 250]}>
              <Heading1>React Parallax</Heading1>
            </Parallax>
          </ParallaxProvider>
        </BannerSection>

        <DemoSection>
          <ParallaxProvider>
            <Parallax y={['-100px', '800px']}>
              <Heading2>An important heading</Heading2>
            </Parallax>
            <DemoColumns>
              <ParallaxContainer>
                <Parallax y={[100, -200]}>
                  <Column>
                    <Box />
                    <Box />
                    <Box />
                  </Column>
                </Parallax>
              </ParallaxContainer>
              <ParallaxContainer>
                <Parallax y={[50, -50]}>
                  <Column>
                    <Box />
                    <Box />
                    <Box />
                  </Column>
                </Parallax>
              </ParallaxContainer>
            </DemoColumns>
          </ParallaxProvider>
        </DemoSection>
        <DemoSection />
      </PageContent>
    </PageContainer>
  )
}

export default HomePage
