import { FC, useRef } from 'react'
import Head from 'next/head'
import 'locomotive-scroll/dist/locomotive-scroll.css'

// eslint-disable-next-line import/extensions
import pageContent from '../../../data/pages/mission-template.json'

import SectionRenderer from '@components/section-renderer'
import { Heading1, PageContainer, PageContent, BannerSection } from '@components/styled'
import { LocomotiveScrollProvider } from '@context/locomotive-scroll'

const MissionTemplatePage: FC = () => {
  const containerRef = useRef<HTMLDivElement | null>(null)

  return (
    <LocomotiveScrollProvider containerRef={containerRef}>
      <PageContainer>
        <Head>
          <title>{pageContent.title} | React Animations Prototyping</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <PageContent ref={containerRef} data-scroll-container>
          <BannerSection data-scroll-section>
            <Heading1 data-scroll data-scroll-speed="4">
              {pageContent.title}
            </Heading1>
            <p>{pageContent.content}</p>
          </BannerSection>

          <SectionRenderer templates={pageContent.sections as any} />
        </PageContent>
      </PageContainer>
    </LocomotiveScrollProvider>
  )
}

export default MissionTemplatePage
